spring:
  application:
    name: drivers
  kafka:
    consumer:
      bootstrap-servers: 192.168.1.49:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: driver-service
      auto-offset-reset: latest
    producer:
      bootstrap-servers: 192.168.1.49:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      ride-update: ride.update
      ride-requested: ride.requested
      cancel-ride: ride.cancel
  cloud:
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: 
        secret-key: 
    dynamodb:
      endpoint:
  data:
    redis:
      host: 192.168.1.49
      port: 6379
  graphql:
    cors:
      allowed-origins: "*"
      allowed-methods: POST, GET, OPTIONS, PUT, DELETE
      allowed-headers: "*"

redis:
  geo:
    key: drivers:locations

server:
  port: 8082

appsync:
  api-key: 
  url: 
