spring:
  application:
    name: riders
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: rider-service
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 3
        retry.backoff.ms: 1000
    topics:
      ride-requested: ride.requested
      ride-update: ride.update
  cloud:
    aws:
      region:
        static: us-east-2
  graphql:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: POST, GET, OPTIONS, PUT, DELETE
      allowed-headers: "*"

server:
  port: 8081

appsync:
  api-key: da2-xom6c66scrct5hto2si5a6cqpi
  url: https://rwohmolr2jb4jp2pkbqks2jvvu.appsync-api.us-east-2.amazonaws.com/graphql
